/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package PresentacionJFRAME;

import Clases.Usuario;
import FuncionalidadBotones.PanelPedidoNuevo;

/**
 *
 * @author ASUS
 */
public class PanelCajero extends javax.swing.JFrame {

    private final Usuario usuarioActual;

    /**
     * Creates new form PanelCajero
     *
     * @param usuario
     */
    public PanelCajero(Usuario usuario) {

        initComponents();

        this.usuarioActual = usuario;

        NombreCliente.setText(usuario.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Cliente_Nuevo = new javax.swing.JButton();
        pedido_nuevo = new javax.swing.JButton();
        ListarPedidos = new javax.swing.JButton();
        ListarClientes = new javax.swing.JButton();
        regresar_Cajero = new javax.swing.JButton();
        NombreCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Hola!");

        Cliente_Nuevo.setText("CLIENTE NUEVO");
        Cliente_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cliente_NuevoActionPerformed(evt);
            }
        });

        pedido_nuevo.setText("PEDIDO NUEVO");
        pedido_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedido_nuevoActionPerformed(evt);
            }
        });

        ListarPedidos.setText("PEDIDOS");
        ListarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarPedidosActionPerformed(evt);
            }
        });

        ListarClientes.setText("CLIENTES");
        ListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarClientesActionPerformed(evt);
            }
        });

        regresar_Cajero.setText("REGRESAR");
        regresar_Cajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresar_CajeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout
                = new javax.swing.GroupLayout(getContentPane());

        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ListarClientes,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                160,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Cliente_Nuevo,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                160,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(62, 62, 62)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(pedido_nuevo,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                160,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ListarPedidos,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                160,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(NombreCliente)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        220,
                                                        Short.MAX_VALUE)
                                                .addComponent(regresar_Cajero)))
                                .addGap(22, 22, 22))
        );

        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(NombreCliente)
                                        .addComponent(regresar_Cajero))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ListarClientes,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ListarPedidos,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        46,
                                        Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Cliente_Nuevo,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pedido_nuevo,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28))
        );

        pack();

        setLocationRelativeTo(null);
    }// </editor-fold>

    private void Cliente_NuevoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void pedido_nuevoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        PanelPedidoNuevo panel
                = new PanelPedidoNuevo(usuarioActual);

        panel.setLocationRelativeTo(null);

        panel.setVisible(true);

        this.dispose();
    }

    private void ListarClientesActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void ListarPedidosActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void regresar_CajeroActionPerformed(java.awt.event.ActionEvent evt) {

        SelectorDeRol selector
                = new SelectorDeRol(usuarioActual);

        selector.setLocationRelativeTo(null);

        selector.setVisible(true);

        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {

            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(info.getClassName());

                    break;
                }
            }

        } catch (ClassNotFoundException ex) {

            java.util.logging.Logger.getLogger(PanelCajero.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {

            java.util.logging.Logger.getLogger(PanelCajero.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {

            java.util.logging.Logger.getLogger(PanelCajero.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

            java.util.logging.Logger.getLogger(PanelCajero.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {

            // new PanelCajero(usuario).setVisible(true);
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton Cliente_Nuevo;
    private javax.swing.JButton ListarClientes;
    private javax.swing.JButton ListarPedidos;
    private javax.swing.JLabel NombreCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton pedido_nuevo;
    private javax.swing.JButton regresar_Cajero;
    // End of variables declaration
}
